export interface Unit {
	project: string
	address: string
	classType: string
	building: string
	section: string
	salesStartDate: string
	salesEndDate: string
	commissioningDate: string
	unitNumber: string
	floor: string
	roomsCount: string
	totalAreaSqm: string
	livingAreaSqm: string
	layoutType: string
	apartmentConfiguration: string
	unitsPerFloor: string
	balconyOrLoggia: string
	verandaOrTerrace: string
	ceilingHeightM: string
	finishing: string
	finishingCostPerSqmRub: string
	masterBedroom: string
	walkInCloset: string
	bathroomsCount: string
	bathroomType: string
	kitchenType: string
	kitchenAreaSqm: string
	elevatorProximity: string
	viewType: string
	plannedConstructionCostRub: string
	actualStatus: string
	saleDate: string
	actualPricePerSqmRub: string
	actualTotalPriceRub: string
	buyerType: string
	buyersCount: string
	dealType: string
	initialPricePerSqmRub: string
	initialTotalPriceRub: string
	paymentMethod: string
	contractRegistrationDate: string
	discountAmountRub: string
	specialProgramInfo: string
	specialProgramDetails: string
	fileGeneratedDate: string
}