export interface Unit {
	project: string
	address: string
	classType: string
	building: string
	section: string
	salesStartDate: string
	salesEndDate: string
	commissioningDate: string
	unitNumber: string
	floor: number
	roomsCount: number
	totalAreaSqm: number
	livingAreaSqm: number
	layoutType: string
	apartmentConfiguration: string
	unitsPerFloor: number
	balconyOrLoggia: string
	verandaOrTerrace: string
	ceilingHeightM: number
	finishing: string
	finishingCostPerSqmRub: number
	masterBedroom: string
	walkInCloset: string
	bathroomsCount: number
	bathroomType: string
	kitchenType: string
	kitchenAreaSqm: number
	elevatorProximity: string
	viewType: string
	plannedConstructionCostRub: number
	actualStatus: string
	saleDate: string
	actualPricePerSqmRub: number
	actualTotalPriceRub: number
	buyerType: string
	buyersCount: number
	dealType: string
	initialPricePerSqmRub: number
	initialTotalPriceRub: number
	paymentMethod: string
	contractRegistrationDate: string
	discountAmountRub: number
	specialProgramInfo: string
	specialProgramDetails: string
	fileGeneratedDate: string
}
