import type { Unit } from '../model/unit'
import type { RawUnit } from '../model/rawUnit'

export const mapRawUnitToUnit = (raw: RawUnit): Unit => ({
	project: raw['Проект'] ?? '',
	address: raw['Адрес'] ?? '',
	classType: raw['Класс'] ?? '',
	building: raw['Корпус'] ?? '',
	section: raw['Секция'] ?? '',
	salesStartDate: raw['Старт продаж'] ?? '',
	salesEndDate: raw['Окончание продаж'] ?? '',
	commissioningDate: raw['Ввод в эксплуатацию'] ?? '',
	unitNumber: raw['№ помещения'] ?? '',
	floor: raw['Этаж'] ?? '',
	roomsCount: raw['Число комнат'] ?? '',
	totalAreaSqm: raw['Общая площадь, кв. м'] ?? '',
	livingAreaSqm: raw['Жилая площадь, кв. м'] ?? '',
	layoutType: raw['Планировка, П/план'] ?? '',
	apartmentConfiguration: raw['Конфигурация квартиры'] ?? '',
	unitsPerFloor: raw['Количество квартир на этаже, шт.'] ?? '',
	balconyOrLoggia: raw['Балкон / Лоджия'] ?? '',
	verandaOrTerrace: raw['Веранда / Терраса'] ?? '',
	ceilingHeightM: raw['Высота потолков, м'] ?? '',
	finishing: raw['Отделка'] ?? '',
	finishingCostPerSqmRub: raw['Стоимость отделки, ₽/кв. м'] ?? '',
	masterBedroom: raw['Мастер-спальня'] ?? '',
	walkInCloset: raw['Гардеробная'] ?? '',
	bathroomsCount: raw['Кол-во санузлов, шт.'] ?? '',
	bathroomType: raw['Тип санузла'] ?? '',
	kitchenType: raw['Тип кухни'] ?? '',
	kitchenAreaSqm: raw['Площадь кухни, кв. м'] ?? '',
	elevatorProximity: raw['Близость к лифту'] ?? '',
	viewType: raw['Вид'] ?? '',
	actualStatus: raw['Статус факт'] ?? '',
	actualPricePerSqmRub: raw['Цена 1 кв. м факт, ₽'] ?? '',
	actualTotalPriceRub: raw['Общая цена факт, ₽'] ?? '',
	plannedConstructionCostRub: raw['Плановая стоимость строительства, руб'] ?? '',
	saleDate: raw['Дата продажи'] ?? '',
	buyerType: raw['Тип покупателя'] ?? '',
	buyersCount: raw['Число покупателей'] ?? '',
	dealType: raw['Тип сделки'] ?? '',
	initialPricePerSqmRub: raw['Цена кв. м на старте продаж, ₽'] ?? '',
	initialTotalPriceRub: raw['Общая цена на старте, ₽'] ?? '',
	paymentMethod: raw['Вариант оплаты'] ?? '',
	contractRegistrationDate: raw['Дата регистрации договора '] ?? '',
	discountAmountRub: raw['Размер скидки, ₽'] ?? '',
	specialProgramInfo: raw['Информация о спецпрограммах'] ?? '',
	specialProgramDetails: raw['Детали спецпрограммы'] ?? '',
	fileGeneratedDate: raw['Дата формирования файла'] ?? '',
})
