import type { Unit } from '../model/unit'
import type { RawUnit } from '../model/rawUnit'

const str = (value: string | null | undefined): string => value ?? ''

export const mapRawUnitToUnit = (raw: RawUnit): Unit => ({
	project: str(raw['Проект']),
	address: str(raw['Адрес']),
	classType: str(raw['Класс']),
	building: str(raw['Корпус']),
	section: str(raw['Подъезд']),
	salesStartDate: str(raw['Старт продаж']),
	salesEndDate: str(raw['Окончание продаж']),
	commissioningDate: str(raw['Ввод в эксплуатацию']),
	unitNumber: str(raw['Номер квартиры']),
	floor: str(raw['Этаж']),
	roomsCount: str(raw['Количество комнат']),
	totalAreaSqm: str(raw['Общая площадь']),
	livingAreaSqm: str(raw['Жилая площадь']),
	layoutType: str(raw['Планировка, П/план']),
	apartmentConfiguration: str(raw['Конфигурация квартиры']),
	unitsPerFloor: str(raw['Количество квартир на этаже, шт.']),
	balconyOrLoggia: str(raw['Балкон / Лоджия']),
	verandaOrTerrace: str(raw['Веранда / Терраса']),
	ceilingHeightM: str(raw['Высота потолков, м']),
	finishing: str(raw['Отделка']),
	finishingCostPerSqmRub: str(raw['Стоимость отделки, ₽/кв. м']),
	masterBedroom: str(raw['Мастер-спальня']),
	walkInCloset: str(raw['Гардеробная']),
	bathroomsCount: str(raw['Кол-во санузлов, шт.']),
	bathroomType: str(raw['Тип санузла']),
	kitchenType: str(raw['Тип кухни']),
	kitchenAreaSqm: str(raw['Площадь кухни, кв. м']),
	elevatorProximity: str(raw['Близость к лифту']),
	viewType: str(raw['Вид']),
	actualStatus: str(raw['Статус']),
	actualPricePerSqmRub: str(raw['Цена за 1 кв.м.']),
	actualTotalPriceRub: str(raw['Общая цена']),
	plannedConstructionCostRub: str(raw['Плановая стоимость строительства, руб']),
	saleDate: str(raw['Дата продажи']),
	buyerType: str(raw['Тип покупателя']),
	buyersCount: str(raw['Число покупателей']),
	dealType: str(raw['Тип сделки']),
	initialPricePerSqmRub: str(raw['Цена кв. м на старте продаж, ₽']),
	initialTotalPriceRub: str(raw['Общая цена на старте, ₽']),
	paymentMethod: str(raw['Вариант оплаты']),
	contractRegistrationDate: str(raw['Дата регистрации договора ']),
	discountAmountRub: str(raw['Размер скидки, ₽']),
	specialProgramInfo: str(raw['Информация о спецпрограммах']),
	specialProgramDetails: str(raw['Детали спецпрограммы']),
	fileGeneratedDate: str(raw['Дата формирования файла']),
})
