import type { Unit } from '../models/unit'
import type { RawUnit } from '../models/rawUnit'

export const mapRawUnitsToUnits = (rawUnits: RawUnit[]): Unit[] =>
	rawUnits.map((raw) => ({
		project: raw['Проект'].toString(),
		address: raw['Адрес'].toString(),
		classType: raw['Класс'].toString(),
		building: raw['Корпус'].toString(),
		section: raw['Секция'].toString(),
		salesStartDate: raw['Старт продаж'].toString(),
		salesEndDate: raw['Окончание продаж'].toString(),
		commissioningDate: raw['Ввод в эксплуатацию'].toString(),
		unitNumber: raw['№ помещения'].toString(),
		floor: raw['Этаж'].toString(),
		roomsCount: raw['Число комнат'].toString(),
		totalAreaSqm: raw['Общая площадь, кв. м'].toString(),
		livingAreaSqm: raw['Жилая площадь, кв. м'].toString(),
		layoutType: raw['Планировка, П/план'].toString(),
		apartmentConfiguration: raw['Конфигурация квартиры'].toString(),
		unitsPerFloor: raw['Количество квартир на этаже, шт.'].toString(),
		balconyOrLoggia: raw['Балкон / Лоджия'].toString(),
		verandaOrTerrace: raw['Веранда / Терраса'].toString(),
		ceilingHeightM: raw['Высота потолков, м'].toString(),
		finishing: raw['Отделка'].toString(),
		finishingCostPerSqmRub: raw['Стоимость отделки, ₽/кв. м'].toString(),
		masterBedroom: raw['Мастер-спальня'].toString(),
		walkInCloset: raw['Гардеробная'].toString(),
		bathroomsCount: raw['Кол-во санузлов, шт.'].toString(),
		bathroomType: raw['Тип санузла'].toString(),
		kitchenType: raw['Тип кухни'].toString(),
		kitchenAreaSqm: raw['Площадь кухни, кв. м'].toString(),
		elevatorProximity: raw['Близость к лифту'].toString(),
		viewType: raw['Вид'].toString(),
		actualStatus: raw['Статус факт'].toString(),
		actualPricePerSqmRub: raw['Цена 1 кв. м факт, ₽'].toString(),
		actualTotalPriceRub: raw['Общая цена факт, ₽'].toString(),
		plannedConstructionCostRub: raw['Плановая стоимость строительства, руб'].toString(),
		saleDate: raw['Дата продажи'].toString(),
		buyerType: raw['Тип покупателя'].toString(),
		buyersCount: raw['Число покупателей'].toString(),
		dealType: raw['Тип сделки'].toString(),
		initialPricePerSqmRub: raw['Цена кв. м на старте продаж, ₽'].toString(),
		initialTotalPriceRub: raw['Общая цена на старте, ₽'].toString(),
		paymentMethod: raw['Вариант оплаты'].toString(),
		contractRegistrationDate: raw['Дата регистрации договора '].toString(),
		discountAmountRub: raw['Размер скидки, ₽'].toString(),
		specialProgramInfo: raw['Информация о спецпрограммах'].toString(),
		specialProgramDetails: raw['Детали спецпрограммы'].toString(),
		fileGeneratedDate: raw['Дата формирования файла'].toString(),
	}))
